Application/DigitaleAssistenter/Models/Attachment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitaleAssistenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public int ProcessId { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public byte[] File { get; set; }
    
        public virtual Process Process { get; set; }
    }
}

Application/DigitaleAssistenter/ViewModels/AttachmentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DigitaleAssistenter.ViewModels
{
    public class AttachmentViewModel
    {
        public int AttachmentId { get; set; }

        [Display(Name = "Proces")]
        [Required]
        public int ProcessId { get; set; }

        [Display(Name = "Filnavn")]
        [MaxLength(500)]
        [Required]
        public string FileName { get; set; }

        [Display(Name = "Filtype")]
        [MaxLength(150)]
        [Required]
        public string ContentType { get; set; }

        [Display(Name = "Fil")]
        [Required]
        public byte[] File { get; set; }
    }
}

Application/DigitaleAssistenter/Controllers/AttachmentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DigitaleAssistenter.Classes;
using DigitaleAssistenter.Models;
using DigitaleAssistenter.ViewModels;

namespace DigitaleAssistenter.Controllers
{
    public class AttachmentController : Controller
    {
        private readonly DigitaleAssistenterEntities _db = new DigitaleAssistenterEntities();
        private readonly int _userId = UserInfoHelpers.GetUserId();
        private readonly bool _isAdmin = System.Web.HttpContext.Current.User.IsInRole(ConfigurationManager.AppSettings["AdminGroup"]);

        public ActionResult DownloadAttachment(int attachmentId)
        {
            var attachment = _db.Attachment.SingleOrDefault(a => a.AttachmentId == attachmentId);

            if (attachment == null) return HttpNotFound();
            if (!_isAdmin && attachment.Process.ConfidentialProcess == true && attachment.Process.CreatedByEmployeeId != _userId && attachment.Process.ReporterEmployeeId != _userId) return new HttpUnauthorizedResult();

            byte[] fileBytes = attachment.File;
            string fileName = attachment.FileName;

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        [HttpPost]
        public ActionResult DeleteAttachment(int attachmentId)
        {
            var attachment = _db.Attachment.SingleOrDefault(a => a.AttachmentId == attachmentId);

            if (attachment == null) return HttpNotFound();
            if (!_isAdmin && attachment.Process.CreatedByEmployeeId != _userId && attachment.Process.ReporterEmployeeId != _userId) return new HttpUnauthorizedResult();

            _db.Attachment.Remove(attachment);
            _db.SaveChanges();

            var attachments = Mapper.Map<List<AttachmentViewModel>>(_db.Attachment.Where(a => a.ProcessId == attachment.ProcessId).ToList());

            return PartialView("PartialViews/_Attachments", attachments);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Application/DigitaleAssistenter/Views/Shared/PartialViews/_Attachments.cshtml
@model List<DigitaleAssistenter.ViewModels.AttachmentViewModel>

<div class="form-group">
    <div class="col-md-3">
        <label class="control-label">Bilag</label>
        <span class="help-block">F.eks. procestegninger, skærmbilleder eller anden dokumentation af processen. Hold CTRL nede for at markere flere filer.</span>
    </div>
    <div class="col-md-9">
        @if (Model != null && Model.Count > 0)
        {
            foreach (var attachment in Model)
            {
                <a href="@Url.Action("DownloadAttachment", "Attachment", new {attachmentId = attachment.AttachmentId })">@attachment.FileName</a> <text>|</text> <a href="#" data-attachment-id="@attachment.AttachmentId" class="delete-attachment">Slet</a>
                <br />
            }
        }
        else
        {
            <input type="file" id="UploadedFile" name="UploadedFile" multiple />
        }
    </div>
</div>